/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AlbumDialog: typeof import('./src/components/AlbumDialog.vue')['default']
    AlbumFileDialog: typeof import('./src/components/AlbumFileDialog.vue')['default']
    AlbumItem: typeof import('./src/components/AlbumItem.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FileInfo: typeof import('./src/components/FileInfo.vue')['default']
    FileItem: typeof import('./src/components/FileItem.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FolderDialog: typeof import('./src/components/FolderDialog.vue')['default']
    FolderItem: typeof import('./src/components/FolderItem.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    GeoLocator: typeof import('./src/components/GeoLocator.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    Image: typeof import('primevue/image')['default']
    InfoDrawer: typeof import('./src/components/InfoDrawer.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RadioButtonGroup: typeof import('primevue/radiobuttongroup')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    ShareDialog: typeof import('./src/components/ShareDialog.vue')['default']
    ShareDialogPublic: typeof import('./src/components/ShareDialogPublic.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    TrashUtilityBar: typeof import('./src/components/TrashUtilityBar.vue')['default']
    UploadFileDialog: typeof import('./src/components/UploadFileDialog.vue')['default']
    UtilityBar: typeof import('./src/components/UtilityBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
